### ISSUE TITLE
Has this plugin been folded into MyBB core?

### ISSUE THREAD

**Issue by dandv** [tommm/StopForumSpam#3]
Stop Forum Spam is now an option under Configuration -> Settings, and works fine with 1.8.3 (see #1).

Was it folded into MyBB core?

CC @PirataNervo, @Stefan-ST, @JN-Jones, @ATofighi, @Destroy666x, @euantorano

**Comment by euantorano** [comment]
Yes, this is core in 1.8 as part of the anti spam improvements made.

**Comment by dandv** [comment]
Thanks. I posted [a question about it on the forum](http://community.mybb.com/thread-164429.html).

**Comment by DiogoParrinha** [comment]
Hi @dandv we'd appreciate if you used to forums to ask questions. GH issues are only for bug reports, enhancements or feature discussions and these must be created by us. Please follow the guidelines :) Thank you.

**Comment by euantorano** [comment]
@PirataNervo This isn't a MyBB repo anyway :smile: @TommM isn't keeping his stuff updated either I believe.

**Comment by DiogoParrinha** [comment]
Ah sorry my bad!

**Comment by dandv** [comment]
You guys are real sticklers for not using GitHub, aren't you? :-)

**Comment by DiogoParrinha** [comment]
Yes, we have our own reasons for having these guidelines.

**Comment by dandv** [comment]
Are you certain these reasons are helping you towards your goals?

(What are your goals? 200 Strong participation from developers on GitHub doesn't seem to be among them)

**Comment by euantorano** [comment]
Our goals are to make life as easy as possible for dev. I've stated my opinion on the "guidelines" (rules) in the past, but ignoring them doesn't get you anywhere. I'd love to just do everything via GitHub, but using the forum allows for people who don't use GitHub. Things may change in the future, but for now it's hardly much effort to post a thread on the forums.

**Comment by dandv** [comment]
"People who don't use GitHub"? What's so hard about using GitHub?

MyBB support questions of course should be posted on community.mybb.com, but for development questions I don't see why you'd want to isolate away from GitHub. GitHub is where it's at. It beat Sourceforge, BitBucket, Codeplex, anything. The most commonly used open source software is on GitHub - Bootstrap, Font Awesome, Rails, Node.js et cetera.

On GitHub there are all sorts of features to refer to the code: diffs, line comments, issues, @-tagging people and so on. None of those exist on the MyBB forum, and they shouldn't - MyBB is not for code management and discussion.

**Comment by dandv** [comment]
I just hope you realize that seasoned developers who have used GitHub for years and aren't on the forum, will never prefer to use the forum if they want to talk about MyBB development. Your forcing them to use the forum to "make life as easy as possible for dev" will result in these developers just moving on.

**Comment by euantorano** [comment]
Bugs aren't only reported by developers, they're reported by users. We can't expect all users to sign up for a GitHub account to (in some cases) submit a single bug report.

It is my opinion that we should accept issues posted straight to GitHub, but the rest of the team has agreed a common set of guidelines that we all follow. Do I agree with them, no. Do I follow them? Yes. It's really not that difficult.

I'm not disagreeing with you, but derailing issues and pull requests for this kind of argument won't get you anywhere and is of no help to anyone.

**Comment by Destroy666x** [comment]
> but for development questions I don't see why you'd want to isolate away from GitHub.

Because the github tickets are called "issues" for a reason. Not "questions" or "discussions", which we, forum software developers, would like to keep on our community site. 2 out of your 3 tickets were far away from being actual issues, which proves our point. Please simply respect it. Thank you.

As for scaring other developers away with this policy - I don't think that opening a thread on our forum instead of doing it on github should be a big problem for anyone who's really interested in helping.

**Comment by euantorano** [comment]
Also, on a side note, I bet @TommM is getting annoyed with email notifications of replies to this (if he has them enabled) :laughing:

**Comment by DiogoParrinha** [comment]
@dandv we're not asking you to agree with our guidelines, we're only asking you to respect them and to follow them. Thank you.
